// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvxq9OFCPtHPIEFV-KhrKV84v6NLTTmeU',
    appId: '1:690460723347:web:ca9ccd310c8cd3400ba566',
    messagingSenderId: '690460723347',
    projectId: 'tta-scheduler-74aaa',
    authDomain: 'tta-scheduler-74aaa.firebaseapp.com',
    storageBucket: 'tta-scheduler-74aaa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVGsfEETml3J0l_A161WzO09--FQV-_u8',
    appId: '1:690460723347:android:7a0e6317b8cf1af80ba566',
    messagingSenderId: '690460723347',
    projectId: 'tta-scheduler-74aaa',
    storageBucket: 'tta-scheduler-74aaa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzAyiAlJ2Vg-FyyrBjeN2RtZfeoyB6skA',
    appId: '1:690460723347:ios:105e37b9c83d89980ba566',
    messagingSenderId: '690460723347',
    projectId: 'tta-scheduler-74aaa',
    storageBucket: 'tta-scheduler-74aaa.firebasestorage.app',
    iosBundleId: 'com.ttascheduler.ttaScheduler',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvxq9OFCPtHPIEFV-KhrKV84v6NLTTmeU',
    appId: '1:690460723347:web:44f0c86ef28471120ba566',
    messagingSenderId: '690460723347',
    projectId: 'tta-scheduler-74aaa',
    authDomain: 'tta-scheduler-74aaa.firebaseapp.com',
    storageBucket: 'tta-scheduler-74aaa.firebasestorage.app',
  );
}
